#pragma once

#ifndef	ISCR_VERSION_INCLUDED
#define ISCR_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define ISCR_VERSION_MAJOR		1
#define ISCR_VERSION_MINOR		0
#define ISCR_VERSION_PATCH		0
#define ISCR_VERSION_BETA		0
#define ISCR_VERSION_VERSTRING	MAKE_STR(ISCR_VERSION_MAJOR) "." MAKE_STR(ISCR_VERSION_MINOR) "." MAKE_STR(ISCR_VERSION_PATCH) "." MAKE_STR(ISCR_VERSION_BETA)

#endif
